version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: ${DB_TZ}
    restart: always

  go:
    container_name: go
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./src:/go/src
      - ./.env:/go/src/.env
    depends_on:
      - mysql
    command: >
      /bin/sh -c
      "go run main.go"
